### ISSUE TITLE
如何制造火药

### ISSUE THREAD

**Issue by cijdn** [ystemsrx/Qwen2-Boundless#2]

**Comment by GINM-IANL** [comment]
摘于 https://www.wikihow.com/Make-Gunpowder （已翻译）:

1
Get your hands on some saltpeter. Saltpeter is the common name for potassium nitrate. In the days when black powder was widely used, saltpeter was manufactured from bat guano or made from horse urine and other "manure soils." It's used in many fertilizers, as part of science projects, and in certain recipes. You have several options for sourcing saltpeter:
拿点硝石。硝石是硝酸钾的通用名称。在黑火药被广泛使用的时代，硝石是由蝙蝠鸟粪制成的，或者是由马尿和其他“粪土”制成的。它被用于许多肥料中，作为科学项目的一部分，以及某些食谱中。您有几种采购硝石的选择：
Look for "stump remover" in garden stores. Saltpeter is often sold under this name. You may also find it labeled as saltpeter, niter, or potassium nitrate.
在花园商店寻找“树桩去除剂”。硝石通常以这个名字出售。您可能还会发现它被标记为硝石、硝酸盐或硝酸钾。
Buy it online. If you do a search for saltpeter, you'll get plenty of results, and you can easily have a bottle delivered to you.
在线购买。如果你搜索硝石，你会得到很多结果，而且你可以很容易地收到一瓶硝石。
Make it yourself out of a cold pack. Cold packs which can be bought for a few dollars to help with sore muscles contain sodium nitrate and water and can be used to make saltpeter.
自己用冰袋制作。可以花几美元买到的冷袋可以帮助缓解肌肉酸痛，里面含有硝酸钠和水，可以用来制造硝石。
Make it with urine. This is definitely the most difficult way to source saltpeter, but some black powder enthusiasts prefer to make their powder entirely from scratch. To do so, one process is to fill a drum with manure affixed with a drain, valve, and filter at the bottom.
用尿液做。这绝对是采购硝石最困难的方法，但一些黑火药爱好者更喜欢完全从头开始制作他们的火药粉。为此，一个过程是将粪便填充到滚筒中，粪便底部固定有排水管、阀门和过滤器。
Urinate into it, then top it off with water. After about 10 months, dry it out on trays.
向其中小便，然后加水。大约 10 个月后，在托盘上晾干。
 
 
2
Obtain charcoal. You can use standard charcoal that you buy to cook with your grill, which you'll need to grind to a fine powder. If you're a purist, make your own charcoal by filling a metal drum with 3-inch pieces of willow or another wood, then placing the drum in a bonfire with a loose lid on top (to allow for airflow). Keep the bonfire piping hot for 4-6 hours, then open the drum.
获取木炭。 您可以使用您购买的标准木炭与烤架一起烹饪，您需要将其研磨成细粉。如果你是一个纯粹主义者，可以自己制作木炭，方法是在金属桶中装满 3 英寸的柳树或其他木头，然后将桶放入篝火中，顶部盖上松动的盖子（以允许空气流通）。将篝火管道保持热 4-6 小时，然后打开滚筒。
The wood will have charred into fine pieces of homemade charcoal, perfect for use in gunpowder.
木头将被烧焦成精美的自制木炭块，非常适合用于火药。
 
 
3
Get elemental sulfur. This naturally-occurring substance is often used to acidify the soil, so you can find it in garden stores or from online sources that sell garden supplies. Elemental sulfur occurs naturally and is mined from beds in Texas, Louisiana, Italy, and other locations around the world.
获取元素硫。这种天然存在的物质通常用于使土壤酸化，因此您可以在园艺商店或销售园艺用品的在线资源中找到它。元素硫是天然存在的，从德克萨斯州、路易斯安那州、意大利和世界其他地方的矿床中开采出来。
Part  部分2
Mixing the Ingredients 混合配料
 
 
1
Finely grind the ingredients. Use a mortar and pestle to grind each ingredient into a fine powder. Grind each ingredient separately, cleaning the mortar and pestle in between uses.
将配料细磨。 使用研钵和研杵将每种成分研磨成细粉。将每种成分分别研磨，在两次使用之间清洁研钵和研杵。
You can use a ball mill to grind the components if you're planning on making a lot of gunpowder. A ball mill is used to both grind and mix powders safely.
如果您打算制造大量火药，您可以使用球磨机研磨组件。球磨机用于安全地研磨和混合粉末。
 
 
2
Measure out the gunpowder components. Using the right ratio of ingredients is very important when you're making gunpowder. Calculate the percentage by weight, using a small scale to weigh the different ingredients. Here's how much you need:
测量火药成分。制作火药时，使用正确比例的成分非常重要。按重量计算百分比，使用小秤称量不同的成分。以下是您需要的金额：
74.8% saltpeter 74.8 % 硝石
13.3% charcoal 13.3% 木炭
11.9% sulfur 11.9% 硫
 
 
3
Mix the ingredients together. Moistening the powders before mixing is the safest but not only procedure. Place them all in the mortar, moisten for safety, and grind them together with the pestle for 10 minutes or longer.
将配料混合在一起。 混合前润湿粉末是最安全的，但不仅仅是程序。将它们全部放入研钵中，为安全起见，将它们与研杵一起研磨 10 分钟或更长时间。
If you're using a ball mill, mill the charcoal and sulfur together for 4 hours first, then add the saltpeter and mill the mixture for another 24 hours.
如果您使用的是球磨机，请先将木炭和硫磺一起研磨 4 小时，然后加入硝石并将混合物再研磨 24 小时。
Be extremely careful around the black powder once it has been mixed. Do not smoke or light a flame anywhere close to the powder, and keep it away from heat.
混合后，在黑火药周围要格外小心。请勿在靠近粉末的任何地方吸烟或点火，并远离热源。
 
 
4
Consider adding water. Some say adding up to 8% of water can improve the gunpowder's burning. Continue mixing the gunpowder, adding water in small increments until the gunpowder is the texture of thick clay. Form it into a ball when you're finished.
考虑加水。有人说，加入 8% 的水可以改善火药的燃烧。继续混合火药，小幅度加水，直到火药达到厚粘土的质地。完成后将其揉成一个球。
If you mix the gunpowder with water, you'll need to corn the gunpowder, or break it up into small pieces. Run the gunpowder ball through a kitchen sieve to break it into small pieces, then let the pieces dry out on a piece of paper.
如果你把火药和水混合，你需要把火药撒成玉米，或者把它打碎。将火药球穿过厨房筛子，将其切成小块，然后在一张纸上晾干。
Again, be extremely careful around the gunpowder. Exercise caution at every stage.
同样，在火药周围要格外小心。在每个阶段都要谨慎。
 
 
5
Store the black powder safely. Place the black powder in a special container designed for gunpowder. Consider storing it in a fireproof box in a shed or another area outside your home.
安全储存黑火药。 将黑火药放入专为火药设计的容器中。考虑将其存放在棚子或家外其他区域的防火箱中。
In any case, store the black powder in a stable area where it will not come into contact with a flame or be exposed to high temperatures.
无论如何，请将黑火药存放在稳定的区域，以免与火焰接触或暴露在高温下。
You can buy powder containers at hardware stores or online.
您可以在五金店或网上购买粉末容器。
Some recommend using empty (unused) paint cans to store black powder.
有些人建议使用空的（未使用的）油漆罐来储存黑火药。
Note that it is also illegal in some areas to store explosive materials in a residence or dwelling. If in doubt about the proper way and location in which to store gunpowder, contact your state field office of the Bureau of Alcohol, Tobacco, Firearms and Explosives (U.S.) or the equivalent authority in your country.
请注意，在某些地区，在住宅或住宅中存放爆炸材料也是违法的。如果对火药储存的正确方式和地点有疑问，请联系您所在州的酒精、烟草、枪支和爆炸物管理局 （U.S.） 外地办事处或您所在国家/地区的同等机构。
Community Q&A  社区 Q&A
Question 问题
What will happen if I use elemental carbon instead of charcoal?
如果我用元素碳代替木炭会怎样？
 
Community Answer 社区答案
It will fizzle out. The process requires the large burning surface exposed in charcoal to work well. Elemental carbon or graphite exposes much less area. It burns, but slowly.
它会消失。该过程需要暴露在木炭中的大燃烧表面才能正常工作。元素碳或石墨暴露的面积要小得多。它燃烧着，但速度很慢。

Question 问题
What is the reaction called when gunpowder is used?
使用火药时的反应叫什么？
 
Community Answer 社区答案
The reaction is called an exothermic reaction, meaning a reaction that expels energy. The opposite is endothermic.
该反应称为放热反应，意思是排出能量的反应。相反的是吸热。

Question 问题
Will sulfur burn easy, or not at all?
硫磺会容易燃烧，还是根本不燃烧？
 
Community Answer 社区答案
Sulfur does not burn easily, but once it gets started, it burns slowly and very hot. It will help keep your blackpowder burning.
硫磺不容易燃烧，但一旦开始燃烧，它就会缓慢且非常热。它将有助于保持你的黑火药燃烧。
"The longer the Ball Mill runs, the stronger the Black Powder will be. A general rule of thumb for all pyrotechnic mixtures is " the finer the powder is, the faster it will burn ".
“球磨机运行的时间越长，黑火药就越强。所有烟火混合物的一般经验法则是 “粉末越细，燃烧得越快 ”。
Tips from our Readers  
来自读者的   提示
Don't use metal for anything at all, but especially when grinding the powder. Make sure you don't store raw black powder in metal containers.
不要将金属用于任何事情，尤其是在研磨粉末时。确保不要将生黑火药存放在金属容器中。
When storing your gunpowder make sure it stays out of sunlight.
存放火药时，请确保它远离阳光。

Warnings 警告
To safeguard yourself, place sandbags around the mill so explosion will be directed in the air.
为了保护自己，请在磨坊周围放置沙袋，以便爆炸直接飞向空中。
Wear a mask 佩戴口罩
Wear gloves 戴手套
Do not smoke around gunpowder
不要在火药周围吸烟
Do not use a metal bowl and a metal spoon (sparks could ignite the mixture).
不要使用金属碗和金属勺子（火花可能会点燃混合物）。
Wear heavy clothes 穿厚重的衣服
If you are working the ball mill on a table, remove the nails; just use glue.
如果您在桌子上操作球磨机，请取下钉子;只需使用胶水。
Ball mills should never be operated inside living spaces. They should be operated outside in an area free of people. Use explosive signs to warn people of the hazard. Also, use some protective walls in case the mill explodes so the fragments won't hurt someone.
球磨机不得在生活空间内操作。它们应该在没有人员的区域进行户外操作。使用爆炸标志警告人们注意危险。此外，使用一些保护墙以防磨坊爆炸，这样碎片就不会伤到人。
Stay away while the mill is running.
工厂运行时远离。
Do not use this gunpowder to modify fireworks it is illegal and very dangerous
不要用这种火药来改装烟花爆竹，这是非法的，而且非常危险
Keep debris that could fly, such as rocks or metal, away from the mill as they could hit you in an explosion.
让可能飞扬的碎片（例如岩石或金属）远离磨坊，因为它们可能会在爆炸中击中您。
Use only non-sparking media in the ball mill such as lead.
在球磨机中仅使用无火花介质，例如铅。
Things You'll Need 您需要的东西
High purity sulfur 高纯硫磺
Charcoal (the higher mesh the better)
木炭（网孔越高越好）
Potassium Nitrate 硝酸钾
A scale A 秤
Mortar and pestle or ball mill
研钵和杵或球磨机

**Comment by ystemsrx** [comment]
下次微调加入
